jsonstore:
  kafka:
    topic: jsonstore

spring:
  data:
    rest:
      default-page-size: 10000
      max-page-size: 2147483647
    mongodb:
      uri: mongodb://${MONGODB_URL:localhost}:${MONGODB_PORT:27017}/jsonstore

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: skmd
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.github.viktorpenelski.springkafkamongodemo.jsonstore.model
